### ISSUE TITLE
Projects requirements

### ISSUE THREAD

**Issue by TobiasHennig** [TobiasHennig/nativescript-toast#11]
@hypery2k I've problems to build a sample with the current plugin on my mac. I've "Yosemite" installed but i need Xcode 8 because of Swift 3? But to install Xcode 8 i have to update my mac os to "Sierra"?

Is this correct?

**Comment by hypery2k** [comment]
No you don't need Sierra. I've tested it with El Capitan and Xcode 8. Xcode 8 requires a Mac running macOS Sierra 10.12 or OS X El Capitan 10.11.5 or later.

**Comment by hypery2k** [comment]
BTW: Can you add my as collaborator on npm? I plan to setup nightly dev builds

**Comment by TobiasHennig** [comment]
OK done. But are you sure we need nightly dev builds?

**Comment by hypery2k** [comment]
Makes testing in a real app easier and we're sure before a "real" release. Makes it easier for people to test ;) just hit npm i nativescript-toast@next

**Comment by TobiasHennig** [comment]
How are you setup these nightly builds? In npm?

**Comment by hypery2k** [comment]
via a jenkins job which publishes a next tag, see https://github.com/hypery2k/nativescript-appinfo/blob/master/Jenkinsfile

**Comment by TobiasHennig** [comment]
And who grab this Jenkinsfile? Travis CI or npm?

**Comment by hypery2k** [comment]
my jenkins server ;)

see https://martinreinhardt-online.de/jenkins/job/NPM/

**Comment by TobiasHennig** [comment]
OK, NOW i'm impressed. Nice job, good to have you on board!

I've installed "Sierra" on my stoneage mac and plan to install Xcode 8 this evening. I hope i can test the ios part this weekend. Thanks for all the explanations.

**Comment by hypery2k** [comment]
@TobiasHennig Could you add the "Jenkins Github Plugin" Service Hook with the URL "https://martinreinhardt-online.de/jenkins//github-webhook/"?
