### ISSUE TITLE
[iOS]: Wrong pod reference 

### ISSUE THREAD

**Issue by TobiasHennig** [TobiasHennig/nativescript-toast#13]
The ios version use the old **JLToast** but the pod reference the new **Toaster**. Following error occured: `file:///app/tns_modules/nativescript-toast/toast.js:9:19: JS ERROR ReferenceError: Can't find variable: JLToast`

**Comment by TobiasHennig** [comment]
I think it should be `Toast(...)` instead of `Toaster(...)` according to the [Toaster documentation](https://github.com/devxoul/Toaster). 
But now im getting the following error: `file:///app/tns_modules/nativescript-toast/toast.js:9:17: JS ERROR Error: Value must be a Pointer.`
Any ideas?

**Comment by hypery2k** [comment]
yes you're right. Don't know what the error means, but you can try this: console.log(JSON.stringify(Toast)) in line 9
