### ISSUE TITLE
Crashes on Android if used during the app launchEvent

### ISSUE THREAD

**Issue by erjdriver** [TobiasHennig/nativescript-toast#14]
In my app.ts file, I have:

`app.on(app.launchEvent, function (args)
{
            Toast.makeText("APP LAUNCHED").show();            
}
`
It crashes on a Context.getResources() null object reference exception.

I put a setTimeout() of 5 seconds and still the same.

This is Android.

**Comment by hypery2k** [comment]
can you tell a little more about your setup? What versions of the plugin and nativescript are you using?

**Comment by erjdriver** [comment]
I've got toast and the Telerik ui plug-in - but I think this can be replicated easily by copying the above line into any {N} app. This is pure {N} on an Android emulator.

I think it might be a limitation of that event function. Even alert() doesn't work - doesn't crash but doesn't display.

**Comment by hypery2k** [comment]
and which package versions you're using?, the current master has a fix for something similar (#8).
But there's currently no new version, as the iOS part is currently failing

**Comment by erjdriver** [comment]
On further review, I'm getting this problem even if I use it after the app is fully running.

I removed and reinstalled the plug-in - same problem.

Here are my plugins.

```
"nativescript-calendar": "^1.0.7",
"nativescript-phone": "^1.1.0",
"nativescript-purchase": "^1.0.0",
"nativescript-telerik-ui-pro": "^1.3.1",
"nativescript-toast": "^1.3.0",
"tns-core-modules": "^2.3.0"
```

**Comment by hypery2k** [comment]
try using nativescript-toast@next

**Comment by erjdriver** [comment]
It works man - it works!!! 

Did you hear me - it works!!!

Same thing during the launchEvent.

Case closed!

**Comment by hypery2k** [comment]
you're welcome

**Comment by erjdriver** [comment]
Oops - jumped the gun.

Works on the emulator but crashes on the device.
