### ISSUE TITLE
Ignore all samples

### ISSUE THREAD

**Issue by bradmartin** [TobiasHennig/nativescript-toast#16]
Just tried building and distributing for iOS today and this plugin will throw errors, at least for me it did. Took me a while to realize it's this plugin (just oversight in the build error email from Apple)

There's really no need to ship any demo or `samples` folder to npm, so I'd suggest adding `samples/` to the .npmignore. I'd submit a PR but I'll let you decide 👍

**Comment by bradmartin** [comment]
Actually would be best to ignore `*.png` `Jenkinsfile`, `.travis.yml` and `sample/` folder so it's not pulled down in the package.

**Comment by hypery2k** [comment]
new version is published

**Comment by bradmartin** [comment]
Nice. Thanks
