### ISSUE TITLE
Set custom duration using setDuration()

### ISSUE THREAD

**Issue by prantikv** [TobiasHennig/nativescript-toast#21]
I see that the plugin has `setDuration(duration: Number): void;` in the `index.d.ts` file.

When I try to uses it as follows the duration is not applied.

```
var toast = Toast.makeText("Hello World");
        toast.setDuration(4000);
        toast.show();
```

Also the getter function `getDuration()` does not work as well.

- Thanks

**Comment by hypery2k** [comment]
that's not possible, see https://developer.android.com/guide/topics/ui/notifiers/toasts.html
