### ISSUE TITLE
Build Error under OS X

### ISSUE THREAD

**Issue by ADjenkov** [TobiasHennig/nativescript-toast#23]
I keep getting:

``
The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64 /Users/djenkov/Work/opencartmobile/platforms/ios/Pods/Toaster/Sources/Toast.swift
	CompileSwift normal arm64 /Users/djenkov/Work/opencartmobile/platforms/ios/Pods/Toaster/Sources/ToastCenter.swift
	CompileSwift normal arm64 /Users/djenkov/Work/opencartmobile/platforms/ios/Pods/Toaster/Sources/ToastView.swift
	CompileSwift normal arm64 /Users/djenkov/Work/opencartmobile/platforms/ios/Pods/Toaster/Sources/ToastWindow.swift
(5 failures)
Command xcodebuild failed with exit code 65`
``

The stack trace is actually bigger with thousands of 

```
/Users/djenkov/Work/opencartmobile/platforms/ios/Pods/Toaster/Sources/ToastWindow.swift:65:29: error: type 'UIColor?' has no member 'clear'
    self.backgroundColor = .clear
                            ^~~~~
/Users/djenkov/Work/opencartmobile/platforms/ios/Pods/Toaster/Sources/ToastWindow.swift:66:5: error: value of type 'ToastWindow' has no member 'isHidden'
    self.isHidden = false
    ^~~~ ~~~~~~~~
/Users/djenkov/Work/opencartmobile/platforms/ios/Pods/Toaster/Sources/ToastWindow.swift:67:5: error: value of type 'ToastWindow' has no member 'handleRotate'
    self.handleRotate(UIApplication.shared.statusBarOrientation)
```
Using {N} 2.5 + Angular 2 . Updated Cocoapods. Updated to Xcode 8.2.1.

**Comment by hypery2k** [comment]
how did you resolved the error?

**Comment by ADjenkov** [comment]
The problem was that after the update from Xcode 7.3 to Xcode 8.2.1 I've had to change my Command Line Tools to Xcode 8.2.1. That didn't happened automatically after the update.

Sorry for the 'spam'
