### ISSUE TITLE
how to use angular2 code in nativescript?

### ISSUE THREAD

**Issue by ghost** [TobiasHennig/nativescript-toast#24]
I have created a web application using angular2 with Node.js .

Now i want to create mobile app for that. using same angular2 code by changes in html page.

So i am in doubt is this possible to use exact code( and little bit change) and exact plugin in Nativescript?

if not, than help me. Thanxx

**Comment by trevordowdle** [comment]
This article might help.

https://www.thepolyglotdeveloper.com/2017/01/display-toast-notifications-nativescript-angular-application/

**Comment by hypery2k** [comment]
```
import * as Toast from 'nativescript-toast';

Toast.makeText('My first toast').show();
```
