### ISSUE TITLE
iOS app crashes with 'Can't find vadiable Toast' in RELEASE only mode.

### ISSUE THREAD

**Issue by ADjenkov** [TobiasHennig/nativescript-toast#26]
{N} 2.5 + Angular 2 on iOS 9.3.5 - my app crashes when try to call `Toast.makeText(....).show()` with

`The ios version use the old JLToast but the pod reference the new Toaster. Following error occured: file:///app/tns_modules/nativescript-toast/toast.js:9:17: JS ERROR ReferenceError: Can't find variable: Toast`

This only happens when I archive the app or in --release .

**Comment by ADjenkov** [comment]
@hypery2k  any help? This is really stopping me to use the plugin in Production mode.

**Comment by ShaimaaKhamees** [comment]
the same here ...and my app was crashed at any event need to show toast...any solution
