### ISSUE TITLE
If using NS Webpack, the build fails

### ISSUE THREAD

**Issue by gaurav-chandra** [TobiasHennig/nativescript-toast#29]
1. Add nativescript webpack
2. add the toast plugin
3. run ```npm run start-android-bundle``` and it fails
![nstoast](https://cloud.githubusercontent.com/assets/3168243/25328700/86118bfc-28f6-11e7-8556-48816b5a7a01.png)

If I remove this plugin, the webpack code is executed fine

**Comment by hypery2k** [comment]
try running `pod repo update`

**Comment by gaurav-chandra** [comment]
No, it did not help.

**Comment by hypery2k** [comment]
which cocoa pod version you're using?
`pod --version`

**Comment by gaurav-chandra** [comment]
1.0.1

**Comment by hypery2k** [comment]
try to update `sudo gem install cocoapods`

**Comment by gaurav-chandra** [comment]
unfortunately this also did not help. anyways, I will keep searching and update here if I find anything.

**Comment by hypery2k** [comment]
closing due to no response
