### ISSUE TITLE
How to cancel toasts?

### ISSUE THREAD

**Issue by thianlim** [TobiasHennig/nativescript-toast#32]
Hi, great plugin, however I'm wondering how to cancel the Toast that is showing. I show it for errors, and when I have multiple errors, the toasts pop up one by one, but I want to cancel this. Is this possible? Thanks!

**Comment by erkanarslan** [comment]
I think you can use cancel function for this. Read this: https://github.com/TobiasHennig/nativescript-toast/blob/master/index.d.ts
