### ISSUE TITLE
Release new version to npm?

### ISSUE THREAD

**Issue by yuri-becker** [TobiasHennig/nativescript-toast#39]
A few PRs, like migration to Swift 4, have been merged since the last npm release. Since we are getting the plugin from npm and are still getting the Swift 3 warning, would it be possible to release a new build to npm in the near future?

**Comment by hypery2k** [comment]
actually build is failing for a while and the repo owner seems not working on the repo. I will try to make a preview build, but not sure if it's working out

**Comment by hypery2k** [comment]
BTW: There's no Swift 4 migration yret

**Comment by yuri-becker** [comment]
I see. I thought that merge 76df259 was the Swift 4 migration already - sorry for the misunderstanding.

**Comment by hypery2k** [comment]
my issue is still open: https://github.com/devxoul/Toaster/issues/139

will give SBToaster a try 2.1.2 It's a fork with my Swift 4 PR

**Comment by hypery2k** [comment]
you can give `nativescript-toast@2.0.0-preview` a try

**Comment by hypery2k** [comment]
Fixed in [Version 2.0.0](https://github.com/TobiasHennig/nativescript-toast/releases/tag/v2.0.0)

**Comment by yuri-becker** [comment]
Great, thanks a lot :)
