### ISSUE TITLE
Enable the `duration` parameter in iOS version

### ISSUE THREAD

**Issue by TobiasHennig** [TobiasHennig/nativescript-toast#5]

**Comment by Daxito** [comment]
Is this working for {N} 1.5.2? it keeps crashing with no error in the log. Testing with ios 9.2 emulator 

Thanks

**Comment by TobiasHennig** [comment]
This has nothing to with the duration parameter, but there was a problem with the pod for iOS. iOS support is dropped with current version 1.3.
