### ISSUE TITLE
 IOs support?

### ISSUE THREAD

**Issue by ryc16** [TobiasHennig/nativescript-toast#9]
Hi, any reason why drop IOS support? Can you enable back IOS support to have consistent interface.

Thanks

**Comment by TobiasHennig** [comment]
I've dropped support because of #6. But @NathanaelA is right, it should work if i set the version. I plan to implement it in the next version, but i'm short on time at the moment.

**Comment by ryc16** [comment]
Thanks. Kindly to add typescripts (the declaration) please.

**Comment by TobiasHennig** [comment]
Should be fixed with release 1.4.
